services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: npm start
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: npm run dev